### ISSUE TITLE
Please document command line options

### ISSUE THREAD

**Issue by radio-miskovice** [pflarue/ardop#108]
Command line options definition (option, usage, what they do) is nowhere to find. IMHO it should be in the README.md or, if too long, specified in a spearate document referred by hyperlink from README.

**Comment by pflarue** [comment]
Jindřich,
Thank you for this.  I recognize that a lot of work is needed to improve documentation, and this needs to be part of it.

For now, typing `ardopcf -h` or `ardopcf --help` shows a summary of command line options.

**Comment by radio-miskovice** [comment]
Hi, if you allow me to publish branch, I will push a new branch with the markdown file in docs. I am almost done :)

**Comment by pflarue** [comment]
Please create a pull request.

For code changes, pull requests should be to the develop branch.  However, pull requests for documentation may be to the master branch.

**Comment by radio-miskovice** [comment]
I created PR into develop branch, pls have a look.
