### ISSUE TITLE
TX drive setting feature request

### ISSUE THREAD

**Issue by k9wkj** [pflarue/ardop#114]
upon launch of ardopcf the TX drive level sets to 100%  
could we have command option to set it to a specific level  ?
a switch like -dr 9   for drive level 9%  (which is what my setup needs)

de k9wkj

**Comment by pflarue** [comment]
This is already possible with the -H or --hostcommands option and the DRIVELEVEL host command.  So, to start ardopcf with 9% TX drive level with the default port of 8515 and audio device plughw:0,0 use:

`ardopcf --hostcommands "DRIVELEVEL 9" 8514 plughw:0,0 plughw:0,0`

--hostcommands can also be used to provide multiple commands to be applied to ardopcf at startup by separating them with semicolons.  So, to set your callsign and set 9% TX drive level with the default port of 8515 and audio device plughw:0,0 use:

`ardopcf --hostcommands "MYCALL K9WKJ;DRIVELEVEL 9" 8514 plughw:0,0 plughw:0,0`
