### ISSUE TITLE
FEC Data buffer FEC declaration repeat bug (FECFEC)

### ISSUE THREAD

**Issue by Dinsmoor** [pflarue/ardop#34]
If the data buffer is loaded with any message and sent, the data buffer
provided to the receiving station's host will always have a double FEC
declaration. If a message is split across multiple frames, only the first
frame in that series will have the double FEC. Not sure if this is
intentional behavior or not, but either way, it is undocumented as far as
I could tell in the source code.

<2 big endian length bytes><mode declaration><data>
             sent		               received
1. x00x05FECHello  | x00x05FECFECHello
2. x00x06FECHappy! | x00x06FECFECHappy!

**Comment by pflarue** [comment]
As described in PR #101, this problems appears to have been the result of a host program created by following some incorrect comments in ProcesReceivedData() in TCPHostInterface.c.  Those comments were corrected by PR #101, which should help to eliminate this problem.
