### ISSUE TITLE
FEC Data buffer repeat bug

### ISSUE THREAD

**Issue by Dinsmoor** [pflarue/ardop#35]
In FEC mode, ARDOPCF will sometimes send data from other frames when a new frame
is received with different data.
(the FECFEC when reading the data buffer on the receive side is a separate bug/Undocumented behavior)

Sending station sends 3 frames with different data content, but same data length.
Format is data sent to sending station buffer | data read from receiving station buffer
<2 big endian length bytes><mode declaration><data>
	         sent		received
1. x00x05FECHello | x00x05FECFECHello
2. x00x05FECHappy | x00x05FECFECHappy
3. x00x05FECNope! | x00x05FECFECHappy

In the debug logs, frames 1, 2, 3 all look fine and normal. 
Frame #3 is wrong, and has a duplicated value of frame #2.

I tested this by sending sequential transmits, where an integer is incremented and sent as an ASCII payload.

The image below is the logs of the receive station, The data sent by the sending station for each, in order were (excluding application headers): TF5, TF6, TF7, but the were received as TF5, TF5, TF5

![Screenshot from 2024-05-22 19-37-14](https://github.com/pflarue/ardop/assets/3772345/374092d5-f3f3-4d42-b034-da8a72b56f60)

I notice that for some reason, although these three frames were sent in a 40 second time period and no frames were missed, they are all Odd frames.

Note that the application (hamChat in my repos) has no control over the frame order.

**Comment by pflarue** [comment]
As described in PR #101, I believe that some of the changes made in that PR should make this sort of error much less likely to occur.  

However, it is possible that this was caused by an unrelated problem.  If this behavior is still observed when using a version of ardopcf incorporating the contents of PR #101, please reopen this Issue.
